import "@/globals.css";
import type { Metadata } from "next";
import * as stylex from "@stylexjs/stylex";
import { globalTokens } from "@/global.stylex";

import { WsDataProvider, ModalProvider, BrowserStoreProvider } from "@/_lib/providers";
import Layout, { Sidebar, Footer } from "./_components/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const styles = stylex.create({
  html: {
    maxWidth: "100vw",
  },
  body: {
    overflowX: "hidden",
    margin: 0,
    padding: 0,
    backgroundColor: globalTokens.bgPrimary,
  },
});

export default ({ children }: { children: React.ReactNode }): JSX.Element => {
  const WS_URL =
    process.env.ENVIRONMENT == "development" ? process.env.WS_URL_DEV : process.env.WS_URL_PROD;
  return (
    <html {...stylex.props(styles.html)} lang="en">
      <body {...stylex.props(styles.body)}>
        <BrowserStoreProvider>
          <WsDataProvider url={WS_URL!}>
            <ModalProvider closeButton={true}>
              <Layout>
                <Sidebar />
                {children}
                <Footer />
              </Layout>
            </ModalProvider>
          </WsDataProvider>
        </BrowserStoreProvider>
      </body>
    </html>
  );
};
