import "@/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { WsDataProvider, ModalProvider, BrowserStoreProvider } from "@/_lib/providers";
import Layout, { Sidebar, Footer } from "./_components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default ({ children }: { children: React.ReactNode }): JSX.Element => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BrowserStoreProvider>
          <WsDataProvider>
            <ModalProvider closeButton={true}>
              <Layout>
                <Sidebar />
                {children}
                <Footer />
              </Layout>
            </ModalProvider>
          </WsDataProvider>
        </BrowserStoreProvider>
      </body>
    </html>
  );
};
